
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.14"
criteria = "safe-to-run"

[[exemptions.anyhow]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.58"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.44"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.6.0"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.6.0"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.iana-time-zone]]
version = "0.1.65"
criteria = "safe-to-deploy"

[[exemptions.id-arena]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.17"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.94"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.184"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.prettyplease]]
version = "0.2.37"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.23.0"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.117"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.117"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.117"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.117"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.94"
criteria = "safe-to-run"

[[exemptions.windows-core]]
version = "0.62.2"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.3"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.48"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.48"
criteria = "safe-to-run"

[[exemptions.zmij]]
version = "1.0.21"
criteria = "safe-to-deploy"
